### ISSUE TITLE
ADMeshGUI on Mac OS X

### ISSUE THREAD

**Issue by hroncok** [vyvledav/ADMeshGUI#1] opened 2015-04-21 17:40 UTC
This is here to tract the status of ADMeshGUI on Mac OS X.

It is a continuation of discussion on https://github.com/admesh/homebrew-admesh/issues/1

**Comment by hroncok** [comment] 2015-04-21 17:43
I've tried to change `menu_bar->setNativeMenuBar (false);` to `true` and it fixed the menubar.

![mac](https://cloud.githubusercontent.com/assets/2401856/7258683/6e8fb54c-e85e-11e4-9ede-d9b8a50518cf.png)

Other problems I see:
- the statistics text is page broken too soon
- the icons bar is not all visible
- the app icon is not set
- some buttons look different than others
- Mac has no middle button, so it would be great to by able to do pan with Shift+LMB

**Comment by syky27** [comment] 2015-04-21 17:45
:+1:

**Comment by hroncok** [comment] 2015-04-21 18:34
Also, the process is literally eating the CPU.

**Comment by vyvledav** [comment] 2015-04-21 18:44
Working on it. CPU usage issue is caused by redrawing based on timer. It is possible to redraw manually on actions done. 
Menubar, text page breaking and pan via Shift+LMB solved.

**Comment by hroncok** [comment] 2015-04-21 20:19
It would be probably also good to set target to ADMeshGUI, to get ADMeshGUI.app

Similar thing to what OpenSCAD is doing:

https://github.com/openscad/openscad/blob/master/openscad.pro#L82

**Comment by hroncok** [comment] 2015-04-22 10:25
The CPU load thing has been fixed.

**Comment by hroncok** [comment] 2015-04-22 11:09
It is not possible to drag and drop files on the icon in dock.

See how it's done in OpenSCAD (I'm repeating myself with this, but they do it the right way) https://github.com/openscad/openscad/blob/master/openscad.pro#L98

**Comment by hroncok** [comment] 2015-04-26 22:50
With the new Plist.info, I can drag and drop STL file to the Icon in the dock, but it leads to no action (aka nothing happens).

I Googled a bit and it seems you have to use this:

http://doc.qt.io/qt-5/qfileopenevent.html

**Comment by syky27** [comment] 2015-04-27 10:03
Hi, so I just updated to new version from HEAD and when I run agmeshgui I have no menu, unless I cycle my windows...

![screenshot 2015-04-27 12 00 10](https://cloud.githubusercontent.com/assets/2771802/7345493/6ae4bcbe-ecd5-11e4-80fd-cfafa24fc411.png)

In case of switching apps the menu appears on second view.

**Comment by syky27** [comment] 2015-04-27 10:25
It's also good practice to have preferences (properties in your case) under `cmd+,` shortcut not `cmd+p`

Every program on mac has it that way. :)

**Comment by hroncok** [comment] 2015-04-27 10:47
> Hi, so I just updated to new version from HEAD and when I run agmeshgui I have no menu, unless I cycle my windows...

@syky27 Apparently only issue with the brew formula

**Comment by hroncok** [comment] 2015-05-03 19:08
I gues sthe last thing now is that the icons in toolbar is not all visible

**Comment by hroncok** [comment] 2015-05-03 19:13
Oh, and this doesn't seem to work https://github.com/vyvledav/ADMeshGUI/blob/2716528785f6580ee9ecd972659715099cdbdea9/data.h#L60

**Comment by vyvledav** [comment] 2015-05-10 11:13
Everything was fixed already so I'am closing this issue.

**Closed as completed by vyvledav** 2015-05-10 11:13 UTC
